Fix ADA/WCAG compliance issues
vercel/commerce pull request #270
Opened 2021-04-13 01:32 UTC by brendanoffer

Hello 👋 , thanks for putting together such a helpful project!

I was scrolling through the page I noticed some ADA / WCAG misses that were easy fixes. These changes help to provide required page context to users with screen readers. 

1. Make the cart icon tab-focusable (everything else in the header is currently focusable but this)
2. Add roles & aria-* tags to the product pages' swatches. Currently there is a generic aria-label that does not provide any context to those using the page. 
3. Add an aria-label to the `ProductCard`'s anchor tag.

2021-05-06 22:26 UTC, okbel approved these changes

2021-06-15 16:44 UTC, brendanoffer commented
@okbel I fixed a merge conflict - please feel free to merge

2021-09-23 00:39 UTC, lfades requested changes
Hi @brendanoffer Thank you for the PR! Could you please fix the conflicts again? 🙏

2021-11-24 14:04 UTC, goncy commented
Hey @brendanoffer, thanks for the PR and sorry for not merging it in time 😓, I will close this PR due to the conflicts being old already but I will create a new PR to ensure this important changes are on the project

2021-11-24 14:04 UTC, closed without merging