Improve a11y on the cart
vercel/commerce pull request #411
Opened 2021-07-08 11:00 UTC by Fedeorlandau

## Improving a11y on the cart

This PR includes:
* A new Button variant `Naked` to wrap SVG buttons. Previously the we had the SVG only.
* Now we can focus on the cart button
* We can close the sidebar by pressing `Escape`
* Focus the sidebar on open.

Regards,

2021-07-08 12:35 UTC, Fedeorlandau commented on components/ui/Sidebar/Sidebar.tsx
> +    if (event.code === 'Escape') {
Please let me know if you find a better way to check this.

2021-07-29 22:44 UTC, lfades requested changes
The cart icon has a different background: https://commerce-bigcommerce-git-fork-8f3229-vercel-solutions-vtest314.vercel.app/

How it should be: https://commerce-bigcommerce-git-fork-438b79-vercel-solutions-vtest314.vercel.app/

2021-07-30 11:52 UTC, Fedeorlandau commented
> Hi there and thank you for the PR!
> 
> The cart icon has a different background: https://commerce-bigcommerce-git-fork-8f3229-vercel-solutions-vtest314.vercel.app/
> 
> How it should be: https://commerce-bigcommerce-git-fork-438b79-vercel-solutions-vtest314.vercel.app/

Fixed. I've just added the `s.item` class to the button to get the dark/light mode behavior.

![image](https://user-images.githubusercontent.com/10283686/127648995-4a623b42-14a5-4b81-ac21-fd5028a54103.png)

![image](https://user-images.githubusercontent.com/10283686/127649039-4d89f642-cc80-47e2-b42f-def5a1dd3a96.png)

Thanks for your feedback

2021-08-30 11:59 UTC, Fedeorlandau commented
Hi @lfades I've fixed the conflicts the the main branch. Hope this get merged soon :) Thanks

2021-09-07 19:10 UTC, lfades commented
@Fedeorlandau LGTM. Thank you and amazing work!

2021-09-07 19:14 UTC, merged