Create checkout on add to cart
vercel/commerce pull request #432
Opened 2021-08-05 05:11 UTC by cond0r

Creates a checkout only when user first time interacts with the cart, not on the first visit of the store #431

2021-08-05 06:14 UTC, ottomated commented
This is promising but I would say it needs both an option to override this behavior and for this to happen on any cart-related action.

2021-08-05 07:09 UTC, cond0r commented
> This is promising but I would say it needs both an option to override this behavior and for this to happen on any cart-related action.

The other cart related  are not active since the cart is empty / null. So you cannot click delete or update. And i just checked. I deleted the cart cookie, and you click on cart again, and the cart was empty, and i was able to click on add to cart, and the cookie & checkout was created again.

2021-09-23 16:06 UTC, goncy requested changes

2021-09-23 16:06 UTC, goncy commented on framework/bigcommerce/cart/use-add-item.tsx
> +  useHook:
Can you revert the changes for this file?

2021-09-23 16:06 UTC, goncy commented on tsconfig.json
> +      "@framework": ["framework/shopify"],
Can you revert this changes?

2021-09-23 16:20 UTC, cond0r commented on tsconfig.json
> +      "@framework": ["framework/shopify"],
@goncy done

2021-09-23 19:57 UTC, lfades requested changes
Hi there and thank you for the PR 👋 

Changes look good to me but the checkout isn't working in the demo: https://commerce-shopify-l41k21i4l-vercel-solutions-vtest314.vercel.app/

2021-09-23 20:28 UTC, cond0r commented
> Hi there and thank you for the PR 👋
> 
> Changes look good to me but the checkout isn't working in the demo: https://commerce-shopify-l41k21i4l-vercel-solutions-vtest314.vercel.app/

I think it as something to do with preview URL's you can see it did the same for the Implement custom checkout one https://commerce-shopify-git-implement-bfb334-vercel-solutions-vtest314.vercel.app/  but is ok in production one

2021-09-24 06:29 UTC, cond0r commented
@lfades now should work. On #487 the handler for checkout was changed to be on submit-checkout file which happens on POST, but since the /checkout is a redirect to /api/checkout, it has GET headers, so changed it to be on get-checkout handler. But what is strange, is that also BigCommerce should require the same changes to work, but works in the production URL now (same with Shopify). But it doesn't work on the preview URL's from the PR for example BigCommerce https://commerce-bigcommerce-git-imple-57f06f-vercel-solutions-vtest314.vercel.app/checkout

2021-09-24 12:52 UTC, goncy commented
> @lfades now should work. On #487 the handler for checkout was changed to be on submit-checkout file which happens on POST, but since the /checkout is a redirect to /api/checkout, it has GET headers, so changed it to be on get-checkout handler. But what is strange, is that also BigCommerce should require the same changes to work, but works in the production URL now (same with Shopify). But it doesn't work on the preview URL's from the PR for example BigCommerce https://commerce-bigcommerce-git-imple-57f06f-vercel-solutions-vtest314.vercel.app/checkout

You are right @cond0r, will take a look at this and get back at you so we can merge this 🙌

2021-09-24 16:43 UTC, goncy commented
@cond0r a PR has been merged to solve this, you can get back to use get-checkout as submit-checkout is not required anymore, thanks! Let me know once its done and I can merge this 🙌

2021-09-24 17:33 UTC, cond0r commented
> @cond0r a PR has been merged to solve this, you can get back to use get-checkout as submit-checkout is not required anymore, thanks! Let me know once its done and I can merge this 🙌

@goncy done, you can check again

2021-09-24 19:55 UTC, goncy approved these changes

2021-09-24 19:55 UTC, merged

2021-09-24 19:55 UTC, goncy commented
Merged, thanks @cond0r!