Feature/hamburger menu
vercel/commerce pull request #540
Opened 2021-10-20 17:23 UTC by ninecodes

- Added Basic Hamburger Menu regarding issue #214 
- Show on smaller screen sizes on the right side of the screen
![image](https://user-images.githubusercontent.com/31674307/138141078-9aedc493-3cdd-46af-adb9-11cea6f557e6.png)

- Basic UI styling for menu items:
![image](https://user-images.githubusercontent.com/31674307/138141179-096c6e77-848f-463d-a4ba-e611d3d53cb5.png)

2021-11-25 16:10 UTC, goncy commented
Hey @ninecodes, this looks awesome! Thanks for it, the only thing we would like (not fully related to this feature), is to make the sidebar full width on mobile, do you want to do it? Otherwise we can merge it and I can do it later

2021-11-25 17:29 UTC, ninecodes commented
> Hey @ninecodes, this looks awesome! Thanks for it, the only thing we would like (not fully related to this feature), is to make the sidebar full width on mobile, do you want to do it? Otherwise we can merge it and I can do it later

Thanks for the feedback, just pushed the mobile full width styling :) hope this is fine :)

2021-11-25 17:37 UTC, goncy commented
@ninecodes It looks great, thanks! Can you fix the conflicts? (they are just prettier conflicts) so we can get this merged now

2021-11-25 17:41 UTC, ninecodes commented
> @ninecodes It looks great, thanks! Can you fix the conflicts? (they are just prettier conflicts) so we can get this merged now

Just resolved them, hope its looking good now :) @goncy

2021-11-25 17:42 UTC, goncy requested changes
This are some small changes if possible!

2021-11-25 17:42 UTC, goncy commented on components/common/UserNav/MenuSidebarView/MenuSidebarView.tsx
> +  console.log(props.links)
Can you remove this log?

2021-11-25 17:42 UTC, goncy commented on components/common/Layout/Layout.tsx
> +  links: any
If its possible we can create a `Link` interface just on top, something like:

```ts
interface Link{
  href: string
  label: string
}
```

And do `links: Link[]`

2021-11-25 17:42 UTC, goncy commented on components/common/Layout/Layout.tsx
> +const SidebarUI: FC<{ links: any }> = ({ links }) => {
You can even extract the links to its own type or interface (or import it from other place) and use that type in here too

2021-11-25 17:43 UTC, goncy commented
Sorry about the back and forth @ninecodes, really appreciate your help 💪

2021-11-25 17:48 UTC, ninecodes commented
> Sorry about the back and forth @ninecodes, really appreciate your help 💪

No worry @goncy just implemented your suggested changes 👍🏼 Hope this helps the project move forward

2021-11-25 18:05 UTC, goncy approved these changes

2021-11-25 18:09 UTC, goncy commented
Awesome @ninecodes thanks! Merged 🙌

2021-11-25 18:09 UTC, merged

2021-11-25 18:11 UTC, ninecodes commented
> Awesome @ninecodes thanks! Merged 🙌

Nice to hear that, will be contributing to other features as well from now on 👍🏼 @goncy

2021-12-10 21:47 UTC, ViktorYermak commented
This mobile menu, like mobile menus in general, is part of an outdated paradigm. A modern user interface should be as visually simple as possible; no hamburgers, no drawers. Therefore, the mobile menu should be optional!