Add lodash.debounce to Shopify provider package.json dependencies
vercel/commerce pull request #691
Opened 2022-02-20 17:44 UTC by lkostrowski

Shopify provider requires `lodash.debounce` package. This package is installed in BigCommerce provider, but not in Shopify provider. After BigCommerce is removed, Shopfify provider can't be installed.

This PR fixes this error

2022-03-15 18:37 UTC, okbel approved these changes

2022-03-15 18:39 UTC, okbel commented
It's been used by multiple providers. Can you add it to site, instead of just the shopify provider?

2022-03-15 18:48 UTC, okbel requested changes
Most providers need debounce. Can you add it to site? Thank you!

2022-03-16 12:13 UTC, lkostrowski commented
@okbel are you sure about that? It doesn't seem like a good way to manage dependencies. Its provider(s) that needs this dep, not client. I suggest adding it to every provider that explicitly needs it, instead of the client implicitly.

2022-03-16 12:15 UTC, okbel commented
If it's not used in the UI (core and site) and it's specific for the provider then let's add it to all of those who are using it.

2022-03-16 12:27 UTC, lkostrowski commented
@okbel done, added to all providers that use debounce (few of them don't)

2022-03-16 14:08 UTC, okbel approved these changes

2022-03-16 14:27 UTC, merged