docs(core): how to run locally
vercel/commerce pull request #716
Opened 2022-03-17 18:05 UTC by dominiksipowicz

The purpose of this PR is to clarify how to run the project locally and highlight the fact that the default provider is just a stripped-down version of a real-life integration.

2022-03-17 18:25 UTC, okbel requested changes

2022-03-17 18:25 UTC, okbel commented on README.md
> +> deafult local provider `@vercel/commerce-local` has disabled all features (cart, auth) and use static files for the backend
deafult typo.

> To run a minimal version of Next.js Commerce you can start with the default local provider...

2022-03-17 18:25 UTC, okbel commented on README.md
> +## Contribute / add new provider
No need

2022-03-17 18:25 UTC, okbel commented on README.md
> +> deafult local provider `@vercel/commerce-local` has disabled all features (cart, auth) and use static files for the backend
Install all dependencies. (There's an issue that pops up - described in the troubleshoot section) Could be useful to point that out.

2022-04-18 16:14 UTC, FranciscoMoretti commented
I just stumbled upon this problem. Thank you for fixing the docs! 👍

2022-04-19 18:19 UTC, okbel approved these changes

2022-04-19 18:19 UTC, merged